language: python
python:
  - "2.7"

install:
  - sudo apt-get update
  - wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py
  - python ./bootstrap.py
  - cctbx-python setup.py install
